# Generated by Django 4.2.4 on 2023-08-08 11:03

from django.db import migrations, models
import django.db.models.deletion
import utils.image_rename


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Crops category name', max_length=355)),
                ('image', models.ImageField(blank=True, help_text='Crops category image', null=True, upload_to=utils.image_rename.crops_category_image)),
            ],
            options={
                'db_table': 'crops_categories',
            },
        ),
        migrations.CreateModel(
            name='DiseasesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Diseases name', max_length=355)),
                ('image', models.ImageField(blank=True, help_text='Diseases image', null=True, upload_to=utils.image_rename.crops_disease_image)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='CropsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Crops name', max_length=355)),
                ('image', models.ImageField(blank=True, help_text='Crops image', null=True, upload_to=utils.image_rename.crops_image)),
                ('description', models.TextField(blank=True, help_text='Crops description', null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops_categories', to='CropApp.cropscategorymodel')),
                ('disease', models.ManyToManyField(related_name='crops_diseases', to='CropApp.diseasesmodel')),
            ],
            options={
                'db_table': 'crops',
            },
        ),
    ]
